"""Export packaging: prompt + control-signal sequences + masks + metadata → zip.

The zip is the hand-off artifact the director feeds to an external AI video
tool (ComfyUI Wan Fun-Control / VACE / LTX, or a commercial platform).
"""

import json
import logging
import re
import time
import traceback
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import cv2
import numpy as np

from app import __version__
from app.db import SessionLocal
from app.models import BackgroundEdit, ExportRecord, LensState, PromptRecord, Shot
from app.services import lens as lens_service
from app.services import paths
from app.services.pipeline import load_extraction_meta
from app.services.task_registry import registry
from app.services.video_io import imwrite_unicode

log = logging.getLogger(__name__)


def _safe_name(name: str, fallback: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\s]+', "_", name).strip("_")
    return cleaned or fallback


def _zip_name(shot: Shot, film_name: str) -> str:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    scene = f"S{shot.scene_no}" if shot.scene_no is not None else "Sx"
    return f"{_safe_name(film_name, 'film')}_{scene}_{_safe_name(shot.name, 'shot')}_V{shot.version}_{stamp}.zip"


def _encode_channel_video(
    frames_dir: Path, out_file: Path, fps: float, progress_cb, channel: str
) -> None:
    import imageio_ffmpeg

    frames = sorted(frames_dir.glob("frame_*.png")) or sorted(frames_dir.glob("frame_*.jpg"))
    if not frames:
        return
    first = cv2.imdecode(np.fromfile(frames[0], dtype=np.uint8), cv2.IMREAD_COLOR)
    h, w = first.shape[:2]
    writer = imageio_ffmpeg.write_frames(
        str(out_file), size=(w, h), fps=max(1.0, fps), codec="libx264", quality=8
    )
    writer.send(None)
    try:
        for i, frame_path in enumerate(frames):
            img = cv2.imdecode(np.fromfile(frame_path, dtype=np.uint8), cv2.IMREAD_COLOR)
            writer.send(cv2.cvtColor(img, cv2.COLOR_BGR2RGB).tobytes())
            if i % 10 == 0:
                progress_cb(i / len(frames), f"encoding {channel}.mp4 {i}/{len(frames)}")
    finally:
        writer.close()


def _readme_text(effective_fps: float, channels: list[str], has_masks: bool) -> str:
    mask_zh = (
        "- masks/：背景改动遮罩（白=改动区域）。edit_<id>.png 与控制帧同分辨率，"
        "edit_<id>_full.png 为原视频分辨率；background_edits.json 记录每个区域的"
        "改动类型与描述，供支持遮罩重绘的工具（如 Wan VACE）使用。\n"
        if has_masks
        else ""
    )
    mask_en = (
        "- masks/: background edit masks (white = edit region). edit_<id>.png matches the\n"
        "  control-frame resolution; edit_<id>_full.png matches the source resolution.\n"
        "  background_edits.json lists each region's intent for masked-editing tools (e.g. Wan VACE).\n"
        if has_masks
        else ""
    )
    return f"""Understudy 导出包使用指南 / Export Package Guide
====================================================

【中文】
本包由 Understudy 生成，用于喂给可控 AI 视频模型（ControlNet 类工作流）。

内容说明：
- prompt.txt / prompt_negative.txt：正/负向提示词，直接粘贴到生成工具。
- frames/：降采样后的原始帧（JPEG），可作 VACE 参考帧或图生视频首帧。
- {' / '.join(channels)}/：控制信号 PNG 序列（frame_000000 起连续编号），
  有效帧率 {effective_fps:.2f} fps。pose/keypoints.json 含逐帧骨架关键点坐标。
- video/：同内容的 H.264 mp4（如已勾选），方便上传网页版生成平台。
{mask_zh}- metadata.json：完整元数据（提取参数、摄影参数、帧索引映射等）。

接入建议：
- ComfyUI + Wan Fun-Control：加载 pose/depth/canny 序列（或 mp4）作为控制视频输入，
  将 prompt.txt 内容填入正向提示词。生成帧率建议匹配有效帧率 {effective_fps:.2f} fps，
  或在生成后按需插帧。
- ComfyUI + VACE：控制序列同上；背景改动用 masks/ 中的遮罩执行 masked video editing。
- LTX-2 / 商业平台：优先使用 video/ 中的 mp4 作为控制输入。

【English】
Generated by Understudy for controllable AI video pipelines (ControlNet-style).

- prompt.txt / prompt_negative.txt: positive & negative prompts, paste as-is.
- frames/: downsampled source frames (JPEG) — VACE reference or first-frame input.
- {' / '.join(channels)}/: control-signal PNG sequences (contiguous from frame_000000),
  effective frame rate {effective_fps:.2f} fps. pose/keypoints.json has per-frame keypoints.
- video/: the same content as H.264 mp4 (if selected) for web-based platforms.
{mask_en}- metadata.json: full metadata (extraction params, cinematography, frame index map).
"""


def run_export_task(task_id: str, shot_id: str, include: dict) -> None:
    db = SessionLocal()
    try:
        registry.start(task_id)
        shot = db.get(Shot, shot_id)
        if shot is None:
            raise RuntimeError("Shot no longer exists")
        film_name = shot.film.name
        shot_dir = paths.shot_dir(shot.film_id, shot.id)
        meta = load_extraction_meta(shot.film_id, shot.id)
        if meta is None:
            raise RuntimeError("Shot has no extraction results")

        prompt = (
            db.query(PromptRecord)
            .filter(PromptRecord.shot_id == shot_id)
            .order_by(PromptRecord.id.desc())
            .first()
        )
        if prompt is None:
            raise RuntimeError("Generate a prompt before exporting")

        edits = (
            db.query(BackgroundEdit)
            .filter(BackgroundEdit.shot_id == shot_id)
            .order_by(BackgroundEdit.sort_order, BackgroundEdit.id)
            .all()
        )

        channels = [c for c in include.get("channels", meta["channels"]) if c in meta["channels"]]
        include_source = bool(include.get("source", False))
        include_videos = bool(include.get("control_videos", True))
        include_masks = bool(include.get("masks", True)) and len(edits) > 0

        exports_dir = shot_dir / "exports"
        exports_dir.mkdir(parents=True, exist_ok=True)
        zip_path = exports_dir / _zip_name(shot, film_name)

        # ---- lens pass: apply zoom to every channel, render dof/focus maps ----
        lens_state = db.get(LensState, shot_id)
        lens = lens_service.normalize_lens(lens_state.data if lens_state else None)
        focus_active = bool(lens["focus"]["enabled"] and lens["focus"]["keyframes"])
        zoom_active = bool(lens["zoom"]["enabled"] and lens["zoom"]["keyframes"])

        channel_dirs: dict[str, Path] = {ch: shot_dir / ch for ch in ["frames", *channels]}
        lens_video_dirs: dict[str, Path] = {}
        keypoints_override: Path | None = None
        lens_tmp = exports_dir / f"_lens_{task_id}"

        if focus_active or zoom_active:
            import shutil

            shutil.rmtree(lens_tmp, ignore_errors=True)
            frame_files = sorted((shot_dir / "frames").glob("frame_*.jpg"))
            total = len(frame_files)
            if zoom_active:
                for ch in channel_dirs:
                    (lens_tmp / ch).mkdir(parents=True, exist_ok=True)
            if focus_active:
                (lens_tmp / "dof").mkdir(parents=True, exist_ok=True)
                (lens_tmp / "focus").mkdir(parents=True, exist_ok=True)

            max_blur = float(lens["focus"]["max_blur"])
            falloff = float(lens["focus"]["falloff"])
            for i in range(total):
                zoom = lens_service.zoom_params_at(lens, i)

                if focus_active:
                    frame = cv2.imdecode(np.fromfile(frame_files[i], np.uint8), cv2.IMREAD_COLOR)
                    depth_path = shot_dir / "depth" / f"frame_{i:06d}.png"
                    if not depth_path.exists():
                        raise RuntimeError("Focus requires the depth channel — extract depth first")
                    depth = cv2.imdecode(np.fromfile(depth_path, np.uint8), cv2.IMREAD_GRAYSCALE)
                    d0 = lens_service.focal_plane_at(lens, i) or 0.5
                    dof, fmap = lens_service.render_dof(frame, depth, d0, max_blur, falloff)
                    if zoom:
                        dof = lens_service.apply_zoom(dof, *zoom)
                        fmap = lens_service.apply_zoom(fmap, *zoom)
                    imwrite_unicode(lens_tmp / "dof" / f"frame_{i:06d}.jpg", dof, quality=88)
                    imwrite_unicode(lens_tmp / "focus" / f"frame_{i:06d}.png", fmap)

                if zoom_active:
                    z = zoom or (1.0, 0.5, 0.5)
                    for ch in channel_dirs:
                        ext = "jpg" if ch == "frames" else "png"
                        src = shot_dir / ch / f"frame_{i:06d}.{ext}"
                        if not src.exists():
                            continue
                        img = cv2.imdecode(np.fromfile(src, np.uint8), cv2.IMREAD_COLOR)
                        imwrite_unicode(
                            lens_tmp / ch / src.name, lens_service.apply_zoom(img, *z), quality=88
                        )

                if i % 10 == 0:
                    registry.set_progress(task_id, 0.25 * i / max(1, total), f"applying lens {i}/{total}")

            if zoom_active:
                channel_dirs = {ch: lens_tmp / ch for ch in channel_dirs}
                # keep pose keypoints aligned with the zoomed frames
                kp_src = shot_dir / "pose" / "keypoints.json"
                if kp_src.exists() and "pose" in channels:
                    ow, oh = meta["output_size"]
                    kp_data = json.loads(kp_src.read_text(encoding="utf-8"))
                    for entry in kp_data.get("frames", []):
                        z = lens_service.zoom_params_at(lens, entry.get("frame", 0))
                        if not z:
                            continue
                        for person in entry.get("people", []):
                            pts = np.array(person["keypoints"], dtype=np.float32)
                            person["keypoints"] = (
                                lens_service.transform_points(pts, ow, oh, *z).round(2).tolist()
                            )
                    keypoints_override = lens_tmp / "keypoints.json"
                    keypoints_override.write_text(
                        json.dumps(kp_data, ensure_ascii=False), encoding="utf-8"
                    )

            if focus_active:
                lens_video_dirs = {"focus_preview": lens_tmp / "dof", "focus": lens_tmp / "focus"}

        # ---- encode mp4s ----
        video_files: dict[str, Path] = {}
        if include_videos:
            tmp_dir = exports_dir / f"_tmp_{task_id}"
            tmp_dir.mkdir(exist_ok=True)
            enc_jobs: list[tuple[str, Path]] = [
                ("source_frames" if ch == "frames" else ch, channel_dirs[ch])
                for ch in ["frames", *channels]
            ] + list(lens_video_dirs.items())
            for idx, (name, src_dir) in enumerate(enc_jobs):
                out_file = tmp_dir / f"{name}.mp4"

                def cb(frac: float, stage: str, _i=idx, _n=len(enc_jobs)):
                    registry.set_progress(task_id, 0.25 + 0.5 * (_i + frac) / _n, stage)

                _encode_channel_video(src_dir, out_file, meta["effective_fps"], cb, name)
                if out_file.exists():
                    video_files[name] = out_file

        ow, oh = meta["output_size"]
        edits_json = [
            {
                "id": e.id,
                "label": e.label,
                "edit_type": e.edit_type,
                "description": e.description,
                "box_norm": {"x": e.x, "y": e.y, "w": e.w, "h": e.h},
                "box_px_out": {
                    "x": round(e.x * ow),
                    "y": round(e.y * oh),
                    "w": round(e.w * ow),
                    "h": round(e.h * oh),
                },
                "mask_out": f"masks/edit_{e.id}.png",
                "mask_full": f"masks/edit_{e.id}_full.png",
            }
            for e in edits
        ]

        metadata = {
            "schema_version": 1,
            "generator": {"app": "Understudy", "version": __version__},
            "created_at": datetime.now(timezone.utc).isoformat(),
            "film": {"id": shot.film_id, "name": film_name},
            "shot": {
                "id": shot.id,
                "name": shot.name,
                "scene_no": shot.scene_no,
                "version": shot.version,
                "tags": shot.tags,
                "notes": shot.notes,
            },
            "video": {
                "filename": shot.source_filename,
                "width": shot.video_width,
                "height": shot.video_height,
                "fps": shot.video_fps,
                "frame_count": shot.video_frame_count,
                "duration_sec": shot.video_duration_sec,
            },
            "extraction": {k: v for k, v in meta.items() if k != "schema_version"},
            "camera_params": prompt.params_snapshot,
            "prompt": {"positive": prompt.positive_prompt, "negative": prompt.negative_prompt},
            "background_edits": edits_json,
            "lens": lens if (focus_active or zoom_active or lens.get("focal")) else None,
            "intended_targets": ["comfyui-wan-fun-control", "comfyui-vace", "ltx-2"],
        }

        registry.set_progress(task_id, 0.75, "packaging zip")
        manifest_files: list[str] = []
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:

            def add_file(src: Path, arcname: str) -> None:
                zf.write(src, arcname)
                manifest_files.append(arcname)

            def add_text(arcname: str, text: str) -> None:
                zf.writestr(arcname, text)
                manifest_files.append(arcname)

            add_text("prompt.txt", prompt.positive_prompt + "\n")
            add_text("prompt_negative.txt", prompt.negative_prompt + "\n")
            add_text(
                "README.txt",
                _readme_text(meta["effective_fps"], channels, include_masks),
            )

            for frame in sorted(channel_dirs["frames"].glob("frame_*.jpg")):
                add_file(frame, f"frames/{frame.name}")
            for channel in channels:
                for frame in sorted(channel_dirs[channel].glob("frame_*.png")):
                    add_file(frame, f"{channel}/{frame.name}")
                kp_file = keypoints_override if (channel == "pose" and keypoints_override) else (
                    shot_dir / channel / "keypoints.json"
                )
                if kp_file.exists():
                    add_file(kp_file, f"{channel}/keypoints.json")

            # focus maps: white = in focus, black = max blur
            if focus_active:
                for frame in sorted((lens_tmp / "focus").glob("frame_*.png")):
                    add_file(frame, f"focus/{frame.name}")

            for channel, file in video_files.items():
                add_file(file, f"video/{file.name}")

            if include_masks:
                for e in edits:
                    for suffix in ("", "_full"):
                        mask = shot_dir / "masks" / f"edit_{e.id}{suffix}.png"
                        if mask.exists():
                            add_file(mask, f"masks/{mask.name}")
                add_text(
                    "masks/background_edits.json",
                    json.dumps(edits_json, ensure_ascii=False, indent=2),
                )

            if include_source:
                source = next((shot_dir / "source").glob("source.*"), None)
                if source:
                    add_file(source, f"source/{source.name}")

            thumb = paths.thumbnail_path(shot.film_id, shot.id)
            if thumb.exists():
                add_file(thumb, "preview/thumbnail.jpg")

            metadata["files"] = manifest_files + ["metadata.json"]
            zf.writestr("metadata.json", json.dumps(metadata, ensure_ascii=False, indent=2))

        # Clean temp workspaces.
        import shutil

        shutil.rmtree(exports_dir / f"_tmp_{task_id}", ignore_errors=True)
        shutil.rmtree(lens_tmp, ignore_errors=True)

        prompt.is_final = True
        record = ExportRecord(
            shot_id=shot_id,
            zip_path=str(zip_path.relative_to(paths.shot_dir(shot.film_id, shot.id))),
            size_bytes=zip_path.stat().st_size,
            manifest=metadata,
            prompt_id=prompt.id,
        )
        shot.status = "exported"
        db.add(record)
        db.commit()

        registry.finish(
            task_id,
            {"export_id": record.id, "zip_name": zip_path.name, "size_bytes": record.size_bytes},
        )
    except Exception as exc:
        log.error("Export task %s failed:\n%s", task_id, traceback.format_exc())
        registry.fail(task_id, str(exc))
    finally:
        db.close()
